### ISSUE TITLE
Searches sometimes come up blank

### ISSUE THREAD

**Issue by wseltzer** [w3c/tr-pages#76]
Some race condition on typing into the form produces a search that shows "## results" but doesn't show those results. (Happens for me frequently in Firefox, it seems, but with no predictable reason.)

**Comment by wseltzer** [comment]
![image](https://user-images.githubusercontent.com/321318/42725982-25b0d082-875b-11e8-8909-bbd0f83d82ae.png)

**Comment by tripu** [comment]
@wseltzer, I can't reproduce this, with FF nor with Chromium&hellip;

Is there no consistent sequence of actions that always triggers this?

Can you check if there are error in the JavaScript console (`Ctrl+Shift+K` before doing anything on the page)?

**Comment by tripu** [comment]
Ah. Found it. I managed to reproduce it. I'm submitting a PR.

**Comment by Kuzcoo** [comment]
@tripu : Hi, still reproducing this bug on the online site. Seems at odd with the master version since you somehow removed the animation applying `display: none` without delay.
I don't understand how the site is built.
Furthermore I had to modify the URL to load the CSS locally.
I think it could help to have more informations on the "contributing" section for newcomers.

**Comment by tripu** [comment]
Thanks for reporting, @Kuzcoo.

(@deniak, ping :innocent:)

**Comment by deniak** [comment]
@tripu thanks for the ping.

@Kuzcoo There's indeed a bug in the way the numbers of specs are computed. This is mainly due to the fact that by default, the "retired" specifications aren't displayed unless you explicitly ask for them in the status drop down list. I'll submit a fix in a bit.

**Comment by deniak** [comment]
https://github.com/w3c/tr-pages/pull/83 should fix the issue. I also updated the link to the CSS so it can work fine locally.

**Comment by Kuzcoo** [comment]
@deniak : still does not work. I commented on #83 
Judging by the name of this pull request I don't know if we talk about the same thing ?
